### ISSUE TITLE
Slack channel for config

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse-ee4j/config#4]
Dear committers, a slack channel `config` was created for Jakarta Config. I have invited the committers whose email address is available to me and the ones who are already in Jakarta EE slack workspace. When you see an slack invitation email, please feel free to join the channel. 

If you have not got the invitation and would like to join, please click this [link](https://jakarta.ee/connect/) and then click on `Join our Slack Workspace`. Once you get into slack workspace, you will see the channel config.

The channel is for some initial brain strom or idea discussion not for decision making.

**Comment by dmlloyd** [comment]
Can we discuss on the call before committing to using Slack?

**Comment by joakime** [comment]
How about just using github discussions instead?
That way it's accessible for everyone, even those that are not participating in slack. (and searchable as part of the general search on this github project)

**Comment by Emily-Jiang** [comment]
If there is an issue raised, sure we will discuss on the github. The slack is for some casual chat. Different people have different preferrence.
