### ISSUE TITLE
Retrieve a portion of overall application configuration

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/config#51]
As a component developer who doesn't know what application my component will belong to, I want my component to retrieve a particular variant of an object representing a portion of my configuration.

**Comment by m0mus** [comment]
As an app developer, I want to be able to assemble configurable modules into an application providing them with their expected configuration (sub-tree) without the need to create a new configuration object. I may use the same module multiple times in a single application with different configuration.

**Comment by ljnelson** [comment]
I disagree with the title edit: retrieving a portion of configuration doesn't _necessarily_ imply a tree structure:
```
HypotheticalConfigSystem.load(
    new TypeLiteralThing<Frobnicator<Map<String, String>>>() {}, 
    "someNameThatIsNotHierarchical.but.maybe.looks.like.it"
);
```
…is an example of loading a portion of overall configuration.  There is no implied connection to any kind of root object, or branch; the `String` here is just a name or a desginator/selector.  The use of "tree" implies an implementation that doesn't have to exist.

**Comment by m0mus** [comment]
@ljnelson Suggest your version of the title, I'll update it.

**Comment by m0mus** [comment]
> As an app developer, I want to be able to assemble configurable modules into an application providing them with their expected configuration (sub-tree) without the need to create a new configuration object. I may use the same module multiple times in a single application with different configuration.

In this case we may need to extract it to the separate issue

**Comment by ljnelson** [comment]
> @ljnelson Suggest your version of the title, I'll update it.

Retrieve a portion of overall application configuration
